### ISSUE TITLE
Unable to run project locally.

### ISSUE THREAD

**Issue by adl1995** [simonsmith/github-user-search#1]
I have cloned your repository and installed all the required packages using `npm install`, but whenever I run `npm start` I get a blank screen on my browser. I have also tried loading the _index.html_ directly but it gives the same result.

webpack seems to bundle everything without any errors, so the problem is somewhere else.

**Comment by simonsmith** [comment]
Did you visit `http://localhost:3001/github-user-search/`?

**Comment by adl1995** [comment]
It worked. Thanks!

Previously, I was visiting `http://localhost:3001/github-user-search` without the leading `/`, so it wasn't pointing to the correct directory.

**Comment by simonsmith** [comment]
@adl1995 Great!

I'll be adding proper documentation when I've finished some other tasks. Feel free to open issues in the meantime.
